name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true
    - name: deploy
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SSH_PROXY_USER: ${{ secrets.SSH_PROXY_USER }}
        SSH_PROXY_ADDR: ${{ secrets.SSH_PROXY_ADDR }}
        SSH_AP_USER: ${{ secrets.SSH_AP_USER }}
        SSH_AP_ADDR: ${{ secrets.SSH_AP_ADDR }}
        SSH_COMMAND: ${{ secrets.SSH_COMMAND }}
      run: |
        mkdir ~/.ssh
        echo $SSH_PROXY_ADDR
        ssh-keyscan $SSH_PROXY_ADDR > ~/.ssh/known_hosts
        echo $SECRET_KEY > secret_key
        ssh -oProxyCommand='ssh -W %h:%p ${SSH_PROXY_USER}@${SSH_PROXY_ADDR} -i ./secret_key' ${SSH_AP_USER}@${SSH_AP_ADDR} -i ./secret_key "$SSH_COMMAND"
